application: helloworld
version: 1
runtime: go
api_version: go1

handlers:
- url: /js
  static_dir: js

- url: /submit
  script: _go_app

- url: /
  static_files: Prototype 2.html
  upload: Prototype 2.html

