application: hattrix-scouting
version: 1
runtime: go
api_version: go1

handlers:
- url: /js
  static_dir: js

- url: /submit
  script: _go_app

- url: /
  static_files: Final 1.html
  upload: Final 1.html
